djangochat/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns(
    '',

    url(r'^$', 'apps.main.views.home_view', name='home'),

    # chat
    url(r'^ajax/chat/add/', 'apps.main.views.chat_add', name='chat-add'),
    url(r'^ajax/chat/get/', 'apps.main.views.chat_get', name='chat-get'),

    # auth
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^registration/$', 'apps.main.views.registration',
        name='registration'),
    url(r'^logout$', 'django.contrib.auth.views.logout', name='logout'),

    # admin
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/models.py
import os
from django.db import models
from django.db.models.signals import post_save


class Message(models.Model):
    name = models.CharField(max_length=55)
    text = models.TextField()
    datetime = models.DateTimeField(auto_created=True)
    file = models.FileField(upload_to='files/', null=True)

    def __str__(self):
        return '%s - %s' % (self.name, self.text[:15])

    @staticmethod
    def log_message(sender, instance, created, **kwargs):
        with open('message_logs.dat', 'a') as p:
            p.write(str(instance)+'\n')

    def filename(self):
        return os.path.basename(self.file.name)


post_save.connect(Message.log_message, sender=Message)

apps/main/forms.py
from datetime import datetime
from .models import Message
from django import forms


class MessageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        self.fields['file'].required = False

    class Meta:
        model = Message
        fields = ('name', 'text', 'file')

    def save(self, *args, **kwargs):
        message = super(MessageForm, self).save(commit=False)
        message.datetime = datetime.now()
        message.save()
        return message

apps/main/views.py
import json

from django.template.loader import render_to_string
from .models import Message
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse
from .forms import MessageForm
from django.shortcuts import render, redirect


def home_view(request, template='index.html'):
    if request.user.is_authenticated():
        return render(request, template, dict(form=MessageForm()))
    return render(request, template)


def registration(request, template='registration/registration.html'):
    if request.method == 'GET':
        context = dict(form=UserCreationForm())
        return render(request, template, context)

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password1'])
            login(request, user)
            return redirect(reverse('home'))
        return render(request, template, dict(form=form))


def chat_add(request):
    form = MessageForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return HttpResponse(json.dumps(dict(success=True)),
                            content_type='application/json')
    return HttpResponse(
        json.dumps(dict(success=False, error_msg='invalid form')),
        content_type='application/json'
    )


def chat_get(request):
    messages = Message.objects.all().order_by('-datetime')[:25]
    return HttpResponse(
        json.dumps(render_to_string(
            'chat_content.html',
            {'messages': reversed(messages), 'user': request.user}
        )),
        content_type='application/json'
    )

apps/main/templates/chat_content.html
{% for message in messages %}

    <div class="left clearfix js-message">
        <div class="chat-body clearfix">
            <div class="header">
                <strong class="primary-font">{{ message.name }}</strong>
                <small class="pull-right text-muted">
                    <span class="glyphicon glyphicon-time"></span>
                    <span class="js-time">{{ message.datetime|date:"Y-m-d H:i:s" }}</span>
                </small>
            </div>
            <p>
                {{ message.text }}

                {% if user.is_authenticated and message.file %}
                    <br>file: <a href="{{ message.file.url }}">{{ message.filename }}</a>
                {% endif %}
            </p>
            <hr>
        </div>
    </div>

{% endfor %}

apps/main/templates/index.html
{% extends "base.html" %}

{% block extra_head %}
    {% load staticfiles %}
    <script src="{% static 'js/main.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/screen.css' %}" media="screen, projection"/>

{% endblock %}

{% block content %}

  <div class="container">
    <h1>Django chat</h1>
    <hr>
    <div class="btn-group" role="group">
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}?next=/" type="button" class="btn btn-default">logout</a>

        {% else %}
              <a type="button" class="btn btn-default" href="{% url 'login' %}">Login</a>
              <a type="button" class="btn btn-default" href="{% url 'registration' %}">Registration</a>
        {% endif %}
    </div>
    <hr>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading"></div>
                <div class="panel-body">
                <div class="chat js-auto-scroll-down" id="container"></div>
                </div>
                <div class="panel-footer">
                    <div class="input-group">
                        {% if user.is_authenticated %}

                            <form id="message" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="text" id="id_name" name="name" class="form-control input-sm" placeholder="Type your Nickname here..." value="{{ user.username }}">
                                <textarea name="text" id="id_text" cols="30" rows="3"  class="form-control input-sm" placeholder="Type your message here..."></textarea>
                                <input type="file" class="form-control input-sm" id="id_file" name="file">
                                <input type="submit" value="message" class="btn btn-warning btn-sm">
                            </form>

                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load staticfiles %}

        <meta charset="utf-8">
        <title>{% block title %}{% endblock title %}</title>

        <meta http-equiv="X-UA-Compatible" content="chrome=IE7" />

        <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />

        <script src="{% static 'js/jquery-2.2.2.min.js' %}"></script>

        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" media="screen, projection"/>

        {% block extra_head %}{% endblock extra_head %}

    </head>
    <body id="{% block body_id %}{% endblock %}" class="{% block body_class %}{% endblock %}">
        {% block content %}{% endblock content %}
    </body>
</html>